#ifndef T1M_SPECIFIC_MEMORY_H
#define T1M_SPECIFIC_MEMORY_H

#include <stdint.h>

typedef enum GAMEALLOC_BUFFER {
    GBUF_TEXTURE_PAGES,
    GBUF_OBJECT_TEXTURES,
    GBUF_MESH_POINTERS,
    GBUF_MESHES,
    GBUF_ANIMS,
    GBUF_ANIM_CHANGES,
    GBUF_ANIM_RANGES,
    GBUF_ANIM_COMMANDS,
    GBUF_ANIM_BONES,
    GBUF_ANIM_FRAMES,
    GBUF_ROOM_TEXTURES,
    GBUF_ROOM_INFOS,
    GBUF_ROOM_MESH,
    GBUF_ROOM_DOOR,
    GBUF_ROOM_FLOOR,
    GBUF_ROOM_LIGHTS,
    GBUF_ROOM_STATIC_MESH_INFOS,
    GBUF_FLOOR_DATA,
    GBUF_ITEMS,
    GBUF_CAMERAS,
    GBUF_SOUND_FX,
    GBUF_BOXES,
    GBUF_OVERLAPS,
    GBUF_GROUNDZONE,
    GBUF_FLYZONE,
    GBUF_ANIMATING_TEXTURE_RANGES,
    GBUF_CINEMATIC_FRAMES,
    GBUF_LOADDEMO_BUFFER,
    GBUF_SAVEDEMO_BUFFER,
    GBUF_CINEMATIC_EFFECTS,
    GBUF_MUMMY_HEAD_TURN,
    GBUF_EXTRA_DOOR_STUFF,
    GBUF_EFFECTS,
    GBUF_CREATURE_DATA,
    GBUF_CREATURE_LOT,
    GBUF_SAMPLE_INFOS,
    GBUF_SAMPLES,
    GBUF_SAMPLE_OFFSETS,
    GBUF_ROLLINGBALL_STUFF,
} GAMEALLOC_BUFFER;

void S_Memory_Init();
void *S_Memory_Alloc(int32_t alloc_size, GAMEALLOC_BUFFER buf_index);
void S_Memory_Free(int32_t free_size, int32_t type);
void S_Memory_Shutdown();

#endif
